a=int(input("enter first num:"))
b=int(input("enter second num:"))
print("addition:",a+b)
print("subtraction:",a-b)
print("multiplication:",a*b)
print("division:",a/b)
print("modulus:",a%b)
print("floor division:",a//b)
